"""
src/generator/toon_generator.py
Converts a SemanticDoc into a .toon document string.

.toon rules:
  @directive value   — one directive per line
  # comment          — comments
    - item           — list items under a multi-value directive
"""
from __future__ import annotations

import re
from typing import Any

from ..parser.normalizer import SemanticDoc

# Keys that map to top-level directives and must not be re-emitted in sections
_TOP_KEYS = {"title", "name", "task", "description", "summary", "tags", "keywords"}


def generate(doc: SemanticDoc, compact: bool = False, pretty: bool = False) -> str:
    lines: list[str] = []
    emitted: set[str] = set()

    def emit(directive: str, value: str = "") -> None:
        slug = _slug(directive)
        if not slug:
            return
        if slug in emitted:
            return
        emitted.add(slug)
        if value:
            lines.append(f"@{slug} {value}")
        else:
            lines.append(f"@{slug}")

    def blank():
        if not compact:
            lines.append("")

    if pretty and not compact:
        lines.append("# Generated by toon-cli")
        lines.append(f"# source: {doc.source_fmt}")
        blank()

    # Core directives
    if doc.title:
        emit("task", _slug(doc.title) or _safe_value(doc.title))
    if doc.description:
        emit("desc", _safe_value(doc.description))
    if doc.tags:
        tag_line = " ".join(_slug(t) for t in doc.tags[:15] if _slug(t))
        if tag_line:
            emit("tags", tag_line)

    # Metadata (flat string → string)
    for k, v in doc.metadata.items():
        if _slug(k) and v and _slug(k) not in _TOP_KEYS:
            emit(k, _safe_value(v))

    # Sections
    for section_name, section_data in doc.sections.items():
        if _slug(section_name) in _TOP_KEYS:
            continue
        if not section_data:
            continue
        s_slug = _slug(section_name)
        if not s_slug:
            continue

        if isinstance(section_data, list):
            blank()
            items = [_safe_value(str(i)) for i in section_data if str(i).strip()]
            if not items:
                continue
            if _all_tokens(items) and len(" ".join(items)) < 80:
                # All single-token items: space-separated (e.g. @tags jwt oauth2)
                emit(s_slug, " ".join(items))
            elif len(", ".join(items)) < 80:
                # Multi-word items that fit inline: comma-separated for readability
                emit(s_slug, ", ".join(items))
            else:
                if s_slug not in emitted:
                    emitted.add(s_slug)
                    lines.append(f"@{s_slug}")
                    for item in items:
                        lines.append(f"  - {item}")

        elif isinstance(section_data, dict):
            blank()
            if pretty:
                lines.append(f"# {section_name}")
            for k, v in section_data.items():
                k2 = _slug(k)
                if k2 and v is not None and k2 not in _TOP_KEYS:
                    emit(k2, _safe_value(str(v)))

        elif isinstance(section_data, str) and section_data.strip():
            emit(s_slug, _safe_value(section_data))

    if not compact and pretty:
        blank()

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------

def _slug(text: str) -> str:
    text = str(text).strip().lower()
    text = re.sub(r"[^a-z0-9_]", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return text[:48]


def _safe_value(text: str) -> str:
    text = re.sub(r"\s+", " ", str(text)).strip()
    return text[:197] + "..." if len(text) > 200 else text


def _all_tokens(items: list[str]) -> bool:
    return all(len(i.split()) == 1 and len(i) <= 30 for i in items)
